/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'authorUsername' : string,
  'text' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'postId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : bigint,
  'text' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Timestamp,
}
export interface Post {
  'id' : bigint,
  'authorUsername' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'caption' : string,
  'image' : ExternalBlob,
}
export interface Profile {
  'bio' : string,
  'username' : string,
  'profilePicture' : ExternalBlob,
}
export interface Reel {
  'id' : bigint,
  'authorUsername' : string,
  'video' : ExternalBlob,
  'author' : Principal,
  'timestamp' : Timestamp,
  'caption' : string,
}
export interface ReelComment {
  'id' : bigint,
  'authorUsername' : string,
  'text' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'reelId' : bigint,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'addReelComment' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[ExternalBlob, string], bigint>,
  'createReel' : ActorMethod<[ExternalBlob, string], bigint>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getAllReels' : ActorMethod<[], Array<Reel>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getConversations' : ActorMethod<[], Array<Principal>>,
  'getFollowerCount' : ActorMethod<[Principal], bigint>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowingCount' : ActorMethod<[Principal], bigint>,
  'getLikeCount' : ActorMethod<[bigint], bigint>,
  'getPost' : ActorMethod<[bigint], Post>,
  'getPostsByUser' : ActorMethod<[Principal], Array<Post>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getReelComments' : ActorMethod<[bigint], Array<ReelComment>>,
  'getReelLikeCount' : ActorMethod<[bigint], bigint>,
  'getReelsByUser' : ActorMethod<[Principal], Array<Reel>>,
  'getSuggestedUsers' : ActorMethod<[], Array<[Principal, Profile]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'hasLiked' : ActorMethod<[bigint], boolean>,
  'hasLikedReel' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'searchPosts' : ActorMethod<[string], Array<Post>>,
  'searchUsers' : ActorMethod<[string], Array<[Principal, Profile]>>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'toggleFollow' : ActorMethod<[Principal], undefined>,
  'toggleLike' : ActorMethod<[bigint], undefined>,
  'toggleReelLike' : ActorMethod<[bigint], undefined>,
  'updateProfile' : ActorMethod<[string, string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];